version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=chdeep
    volumes:
      - data:/data/db
      - config:/data/configdb
  psc-extensions-api:
    image: '416670754337.dkr.ecr.eu-west-2.amazonaws.com/local/psc-extensions-api:latest'
    expose:
      - 8080