spring.application.name=psc-extensions-api

# Spring MongoDB
#todo: update the URL when known
spring.mongodb.uri=${MONGODB_URL:mongodb://mongo/transactions_extensions}
spring.mongodb.database=${MONGODB_DATABASE:transactions_extensions}
management.health.mongodb.enabled=false
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

# Spring Actuator
management.endpoints.access.default=${MANAGEMENT_ENDPOINTS_ACCESS_DEFAULT:none}
management.endpoint.health.access=${MANAGEMENT_ENDPOINT_HEALTH_ACCESS:unrestricted}
management.endpoints.web.path-mapping.health=${MANAGEMENT_ENDPOINTS_WEB_PATH_MAPPING_HEALTH:healthcheck}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH:/persons-with-significant-control-extensions}
management.endpoints.web.exposure.include=health

# LOGGING
logging.level.uk.gov.companieshouse.psc.extensions.api=${LOG_LEVEL:INFO}
logging.level.org.springframework.web=${WEB_LOGGING_LEVEL:INFO}
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=${REQUEST_LOGGING_LEVEL:INFO}
logging.level.org.apache.http=${LOGGING_LEVEL:INFO}

# OpenTelemetry
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
# URLs
internal.api.url=${INTERNAL_API_URL:internal_api_url}
